import { Service } from "@prisma/client";

// Mocking the ID and dates since they are generated by DB
export const FALLBACK_SERVICES: Service[] = [
    {
        id: "fallback-1",
        slug: "web-development",
        isActive: true,
        sortOrder: 1,
        name: "Web Development",
        subName: "Digital Excellence.",
        price: "Custom",
        description: "Next.js 14+ - High Performance - SEO Optimized",
        themeColor: "#00B4D8", // Cyan

        features: ["Next.js App Router", "Server Components", "Edge Caching"],
        stats: [{ label: "Lighthouse", val: "100" }, { label: "Uptime", val: "99.9%" }, { label: "Speed", val: "<100ms" }],
        section1: { title: "Web Development.", subtitle: "Digital Excellence." },
        section2: { title: "Blazing fast performance.", subtitle: "Built on the latest Next.js infrastructure for instant page loads and superior SEO." },
        section3: { title: "Pixel-perfect engineering.", subtitle: "Every interaction is crafted with precision, ensuring a premium user experience across all devices." },
        section4: { title: "Scalable architecture.", subtitle: "" },
        detailsSection: {
            title: "Architecture First",
            description: "We don't just write code; we architect solutions. Using modern frameworks like React and Next.js, we build web applications that scale effortlessly from 100 to 1 million users. Our component-driven development ensures maintainability and rapid iteration.",
            imageAlt: "Web Dev Architecture"
        },
        freshnessSection: {
            title: "Clean Code Guarantee",
            description: "Our codebases are strictly typed with TypeScript and linted for consistency. We adhere to SOLID principles, ensuring that your application remains robust, readable, and easy to extend for years to come."
        },
        buyNowSection: {
            price: "From $5k",
            unit: "per project",
            processingParams: ["SEO Ready", "Analytics", "CMS Integration"],
            deliveryPromise: "Agile delivery with bi-weekly demos. Full source code ownership.",
            returnPolicy: "30-day bug fix warranty included."
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        version: 0,
    },
    {
        id: "fallback-2",
        slug: "mobile-app-development",
        isActive: true,
        sortOrder: 2,
        name: "Mobile Apps",
        subName: "Native Performance.",
        price: "Custom",
        description: "React Native - iOS & Android - Smooth 60FPS",
        themeColor: "#AF52DE", // Purple

        features: ["Cross-Platform", "Native Modules", "Offline Mode"],
        stats: [{ label: "Platforms", val: "2" }, { label: "Code Share", val: "90%" }, { label: "FPS", val: "60" }],
        section1: { title: "Mobile Apps.", subtitle: "Native Performance." },
        section2: { title: "One codebase, everywhere.", subtitle: "React Native allows us to deploy to iOS and Android simultaneously without compromising quality." },
        section3: { title: "Silky smooth animations.", subtitle: "Optimized for 60fps performance with native driver integrations and gesture handling." },
        section4: { title: "Offline-first design.", subtitle: "" },
        detailsSection: {
            title: "Native Experience",
            description: "Users expect performant, responsive apps. We bridge the gap between web and native, accessing device features like Camera, GPS, and Haptics directly to create immersive mobile experiences that feel at home on any device.",
            imageAlt: "Mobile App Logic"
        },
        freshnessSection: {
            title: "Store Approval Support",
            description: "We handle the entire submission process for Apple App Store and Google Play Store, ensuring your app meets all guidelines and gets approved quickly."
        },
        buyNowSection: {
            price: "From $8k",
            unit: "per project",
            processingParams: ["iOS + Android", "Push Notifs", "Biometrics"],
            deliveryPromise: "TestFlight builds delivered weekly.",
            returnPolicy: "Post-launch crash monitoring included."
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        version: 0,
    },
    {
        id: "fallback-3",
        slug: "custom-software-development",
        isActive: true,
        sortOrder: 3,
        name: "Custom Software",
        subName: "Tailored Solutions.",
        price: "Enterprise",
        description: "Microservices - Scalable - Secure",
        themeColor: "#FF9500", // Orange

        features: ["Enterprise Grade", "SaaS Ready", "API First"],
        stats: [{ label: "Security", val: "AES-256" }, { label: "Scale", val: "Unltd" }, { label: "API", val: "REST/QL" }],
        section1: { title: "Custom Software.", subtitle: "Tailored Solutions." },
        section2: { title: "Complex problems, solved.", subtitle: "We maintain rigorous logic to handle intricate business rules and data flows." },
        section3: { title: "Integrated ecosystems.", subtitle: "Seamlessly connect with your existing CRM, ERP, and third-party tools." },
        section4: { title: "Data-driven insights.", subtitle: "" },
        detailsSection: {
            title: "Business Logic Core",
            description: "Off-the-shelf software rarely fits perfectly. We build custom engines tailored to your specific workflows, automating manual processes and unlocking efficiency that generic tools can't match.",
            imageAlt: "Custom Logic"
        },
        freshnessSection: {
            title: "Security by Design",
            description: "We implement defense-in-depth strategies, including role-based access control (RBAC), data encryption at rest and in transit, and regular security audits."
        },
        buyNowSection: {
            price: "Contact Us",
            unit: "per scope",
            processingParams: ["Cloud Native", "Dockerized", "CI/CD Pipeline"],
            deliveryPromise: "Phased rollout with user training.",
            returnPolicy: "SLA-backed support agreements."
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        version: 0,
    },
    {
        id: "fallback-4",
        slug: "ui-ux-design",
        isActive: true,
        sortOrder: 4,
        name: "UI/UX Design",
        subName: "User Centric.",
        price: "Custom",
        description: "Figma - Prototyping - Design Systems",
        themeColor: "#FF2D55", // Pinkish Red

        features: ["User Research", "Wireframing", "Hi-Fi Visuals"],
        stats: [{ label: "Users", val: "Happy" }, { label: "Conversion", val: "+40%" }, { label: "Awards", val: "Yes" }],
        section1: { title: "UI/UX Design.", subtitle: "User Centric." },
        section2: { title: "Designs that convert.", subtitle: "Aesthetics meet function. We design interfaces that guide users naturally towards your goals." },
        section3: { title: "Interactive prototypes.", subtitle: "Visualize the product before writing a single line of code with clickable high-fidelity prototypes." },
        section4: { title: "Accessibility included.", subtitle: "" },
        detailsSection: {
            title: "The Design System",
            description: "We don't just design pages; we build design systems. Reusable components, consistent typography, and unified color palettes ensure your brand remains cohesive across all digital touchpoints.",
            imageAlt: "Design System"
        },
        freshnessSection: {
            title: "Empathy Driven",
            description: "We start with the user. Through persona layout and journey mapping, we identify pain points and design solutions that truly solve user problems."
        },
        buyNowSection: {
            price: "From $3k",
            unit: "per sprint",
            processingParams: ["Figma Files", "Style Guide", "Assets"],
            deliveryPromise: "Developer-ready handover files.",
            returnPolicy: "Unlimited revisions during design phase."
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        version: 0,
    },
    {
        id: "fallback-5",
        slug: "cloud-devops",
        isActive: true,
        sortOrder: 5,
        name: "Cloud & DevOps",
        subName: "Infrastructure.",
        price: "Retainer",
        description: "AWS/Azure - Kubernetes - Terraform",
        themeColor: "#34C759", // Green

        features: ["Auto Scaling", "Cost Optics", "Security Ops"],
        stats: [{ label: "Uptime", val: "99.99%" }, { label: "Deploy", val: "Auto" }, { label: "Cost", val: "-30%" }],
        section1: { title: "Cloud & DevOps.", subtitle: "Infrastructure." },
        section2: { title: "Scale without fear.", subtitle: "Kubernetes clusters that grow with your traffic, handling millions of requests automatically." },
        section3: { title: "GitOps workflows.", subtitle: "Push to git, and let our pipelines handle testing, building, and deploying to production." },
        section4: { title: "Resilient systems.", subtitle: "" },
        detailsSection: {
            title: "Infrastructure as Code",
            description: "We define your entire infrastructure using Terraform or CDKTF. This means your environments are reproducible, version-controlled, and transparent. No more 'it works on my machine'.",
            imageAlt: "Cloud Infra"
        },
        freshnessSection: {
            title: "24/7 Monitoring",
            description: "We set up comprehensive observability with tools like Prometheus and Grafana, giving you real-time insights into system health and alerting you before issues affect users."
        },
        buyNowSection: {
            price: "Contact Us",
            unit: "monthly",
            processingParams: ["AWS/GCP/Azure", "CI/CD Setup", "Audits"],
            deliveryPromise: "Zero-downtime migrations.",
            returnPolicy: "Monthly performance reports."
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        version: 0,
    }
];
